---

- name: copy neovim config
  copy: src=./files/{{ item }}
        dest=/home/{{ user }}/.config/nvim/{{ item }}
        owner={{ user }}
        group={{ user }}
        mode=0640
  with_items:
    - init.vim

- name: copy zsh aliases
  copy: src=./files/{{ item }}
        dest=/home/{{ user }}/.oh-my-zsh/custom/{{ item }}
        owner={{ user }}
        group={{ user }}
        mode=0640
  with_items:
    - aliases.zsh
    - common-aliases.zsh
    - zle.zsh

- name: git config
  copy: src=./files/{{ item }}
        dest=/home/{{ user }}/.{{ item }}
        owner={{ user }}
        group={{ user }}
        mode=0640
  with_items:
    - gitignore
